--- 

- name: install utilities
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache and install utilities
      ansible.builtin.apt:
        name:
          - tcpdump
          - iperf
          - netcat-traditional 
          - curl
          - nload
          - nmap
          - htop
        state: latest
        update_cache: yes
