---
- name: Install Git on all VMs
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Git on Debian/Ubuntu
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
