global:
  scrape_interval: 15s

scrape_configs:
  # Мониторинг самого Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Сбор метрик с Blackbox Exporter для проверки нашего сайта
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx] # Используем модуль http_2xx из blackbox.yml
    static_configs:
      - targets:
          - http://nginx # Проверяем наш Nginx по имени сервиса в Docker-сети
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115 # Адрес Blackbox Exporter